name: assetly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.8
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  reactive_forms: ^16.1.1
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  dio: ^5.3.3
  flutter_easyloading: ^3.0.5
  reactive_pin_code_fields: ^2.0.0
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.64.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/json/